# Generated by Django 4.1.4 on 2022-12-13 09:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_device_amount_changes_device_created_device_last_mod"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consumption", models.IntegerField()),
                (
                    "kind",
                    models.IntegerField(
                        choices=[
                            (0, "Unknown"),
                            (3, "Gate"),
                            (4, "Blind"),
                            (2, "Relay"),
                            (1, "Bulb"),
                        ],
                        default=0,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="device",
            name="created",
            field=models.DateField(
                default=datetime.datetime(2022, 12, 13, 9, 29, 10, 546584)
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="extra_info",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.extrainfo",
            ),
        ),
    ]
