# Generated by Django 4.1.4 on 2022-12-13 14:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_extrainfo_alter_device_created_device_extra_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("desc", models.TextField(max_length=256)),
                ("act_temp", models.FloatField(default=0)),
                (
                    "created",
                    models.DateField(
                        default=datetime.datetime(2022, 12, 13, 14, 16, 19, 639077)
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="device",
            name="created",
            field=models.DateField(
                default=datetime.datetime(2022, 12, 13, 14, 16, 19, 638518)
            ),
        ),
        migrations.AlterField(
            model_name="extrainfo",
            name="kind",
            field=models.IntegerField(
                choices=[
                    (0, "Unknown"),
                    (4, "Blind"),
                    (3, "Gate"),
                    (1, "Bulb"),
                    (2, "Relay"),
                ],
                default=0,
            ),
        ),
        migrations.CreateModel(
            name="SensorHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField(blank=True)),
                (
                    "created",
                    models.DateField(
                        default=datetime.datetime(2022, 12, 13, 14, 16, 19, 639456)
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.sensor"
                    ),
                ),
            ],
        ),
    ]
