# Generated by Django 4.1.4 on 2022-12-13 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_sensor_alter_device_created_alter_extrainfo_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="created",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="created",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="sensorhistory",
            name="created",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
