# Generated by Django 4.1.4 on 2022-12-13 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_device_created_alter_sensor_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrainfo",
            name="kind",
            field=models.IntegerField(
                choices=[
                    (1, "Bulb"),
                    (4, "Blind"),
                    (2, "Relay"),
                    (0, "Unknown"),
                    (3, "Gate"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="sensorhistory",
            name="created",
            field=models.DateField(
                default=datetime.datetime(2022, 12, 13, 14, 23, 29, 953895)
            ),
        ),
    ]
