# Generated by Django 4.1.4 on 2022-12-13 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_extrainfo_kind_alter_sensorhistory_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrainfo",
            name="kind",
            field=models.IntegerField(
                choices=[
                    (4, "Blind"),
                    (2, "Relay"),
                    (3, "Gate"),
                    (0, "Unknown"),
                    (1, "Bulb"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="sensorhistory",
            name="created",
            field=models.DateField(default=datetime.datetime),
        ),
    ]
