# Generated by Django 4.1.4 on 2022-12-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_sensorhistory_updated_alter_extrainfo_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrainfo",
            name="kind",
            field=models.IntegerField(
                choices=[
                    (4, "Blind"),
                    (1, "Bulb"),
                    (3, "Gate"),
                    (0, "Unknown"),
                    (2, "Relay"),
                ],
                default=0,
            ),
        ),
    ]
