# Generated by Django 4.1.4 on 2022-12-13 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_extrainfo_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="extrainfo",
            name="kind",
            field=models.IntegerField(
                choices=[
                    (4, "Blind"),
                    (0, "Unknown"),
                    (3, "Gate"),
                    (2, "Relay"),
                    (1, "Bulb"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="sensorhistory",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="api.sensor",
            ),
        ),
    ]
