# Generated by Django 4.1.4 on 2022-12-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_sensor_updated_alter_extrainfo_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrainfo",
            name="kind",
            field=models.IntegerField(
                choices=[
                    (2, "Relay"),
                    (3, "Gate"),
                    (1, "Bulb"),
                    (4, "Blind"),
                    (0, "Unknown"),
                ],
                default=0,
            ),
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("surname", models.CharField(max_length=32)),
                ("devices", models.ManyToManyField(to="api.device")),
                ("sensors", models.ManyToManyField(to="api.sensor")),
            ],
        ),
    ]
