# Generated by Django 4.1.4 on 2022-12-15 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_device_created_alter_extrainfo_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="extrainfo",
            name="device_kind",
            field=models.CharField(
                choices=[
                    ("UN", "Unknown"),
                    ("BU", "Bulb"),
                    ("RE", "Relay"),
                    ("GA", "Gate"),
                    ("BL", "Blind"),
                ],
                default="UN",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="extrainfo",
            name="kind",
            field=models.IntegerField(
                choices=[
                    (1, "Bulb"),
                    (4, "Blind"),
                    (3, "Gate"),
                    (2, "Relay"),
                    (0, "Unknown"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="sensorhistory",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="histories",
                to="api.sensor",
            ),
        ),
    ]
