# Generated by Django 4.1.4 on 2022-12-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_extrainfo_device_kind_alter_extrainfo_kind_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extrainfo",
            name="kind",
        ),
    ]
