# Generated by Django 4.1.4 on 2022-12-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_device_modbus_register_device_plc_register"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="modbus_register",
        ),
        migrations.RemoveField(
            model_name="device",
            name="plc_register",
        ),
    ]
